name: Auto-posting Bot for Telegram (TEST VERSION)

on:
  # Запускается только вручную для теста
  workflow_dispatch:

jobs:
  build_and_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot script
        # Блок env больше не нужен, так как ключи вшиты в код
        run: python bot_script.py
