name: Telegram Poster

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 6,8,12,15,17 * * *'  # 8,10,14,17,19 по Москве (UTC+3)

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytrends requests Pillow google-genai

    - name: Run Telegram Poster
      run: python immediate_post.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          // Просто логируем ошибку, не пытаемся комментировать issue
          console.log('❌ Публикация в Telegram не удалась!');
          // Можно отправить уведомление в Telegram о ошибке
          const telegramMessage = `❌ Ошибка в GitHub Actions: Публикация не удалась\n\nРепо: ${context.repo.owner}/${context.repo.repo}\nВремя: ${new Date().toLocaleString('ru-RU')}`;
          
          // Опционально: отправка уведомления в Telegram о ошибке
          // await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_TOKEN}/sendMessage`, {
          //   method: 'POST',
          //   headers: { 'Content-Type': 'application/json' },
          //   body: JSON.stringify({
          //     chat_id: process.env.TELEGRAM_CHANNEL_ID,
          //     text: telegramMessage
          //   })
          // });
