name: Publish to Telegram

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 6,8,12,15,17 * * *'  # 8,10,14,17,19 по Белграду (UTC+3)

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytrends requests Pillow

    - name: Run post generator
      run: python immediate_post.py

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Публикация в Telegram не удалась!'
          })
