name: Telegram Poster

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 6,8,12,15,17 * * *'  # 8:00, 10:00, 14:00, 17:00, 19:00 по Москве

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies with specific versions
      run: |
        python -m pip install --upgrade pip
        pip install pytrends==4.9.0
        pip install requests==2.31.0
        pip install Pillow==10.0.1
        pip install pandas==1.5.3
        pip install numpy==1.24.3

    - name: Verify installations
      run: |
        pip list | grep -E "pytrends|requests|Pillow|pandas|numpy"

    - name: Run Telegram Poster
      run: python main.py

    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Публикация в Telegram не удалась!"
        date
