name: Telegram Poster

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 6,8,12,15,17 * * *'  # 8:00, 10:00, 14:00, 17:00, 19:00 по Москве

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytrends requests Pillow

    - name: Verify environment variables
      run: |
        echo "TELEGRAM_TOKEN length: ${#TELEGRAM_TOKEN}"
        echo "TELEGRAM_CHANNEL_ID: $TELEGRAM_CHANNEL_ID"
        echo "GROK_API_KEY starts with: ${GROK_API_KEY:0:10}..."

    - name: Run Telegram Poster
      run: python main.py

    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Публикация в Telegram не удалась!"
        date
