name: Telegram Poster

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 6,8,12,15,17 * * *'  # 8:00, 10:00, 14:00, 17:00, 19:00 по Москве

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytrends requests Pillow python-dotenv

    - name: Create .env file from GitHub Secrets
      run: |
        echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" > .env
        echo "TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}" >> .env
        echo "GROK_API_KEY=${{ secrets.GROK_API_KEY }}" >> .env
        echo "✅ .env file created from GitHub Secrets"

    - name: Run Telegram Poster
      run: python immediate_post.py

    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Публикация в Telegram не удалась!"
        date
